# Generated by Django 4.0.4 on 2022-06-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionHistoric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_name', models.CharField(max_length=15)),
                ('emotion_percentage', models.DecimalField(decimal_places=4, max_digits=4)),
                ('creation_date', models.DateField()),
            ],
        ),
    ]
